name: Conduit_tests_with_pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9.5]

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose up -d

    - name: Sleep for 45 seconds
      run: sleep 45s
      shell: bash

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f selenium_python_tests/requirements.txt ]; then pip install -r selenium_python_tests/requirements.txt; fi

    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable

    - name: Test with pytest
      run: |
        pytest

    - name: Collect docker logs on failure
      uses: jwalton/gh-docker-logs@v1
      with:
        dest: './logs'

    - name: Archive execution artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docker-logs
        path: ./logs

    - name: Archive execution artifacts
      uses: actions/upload-artifact@v2
      with:
        name: application-screenshot
        path: screenshot.png